import { notFound } from "next/navigation";

import { BatchNav } from "@/components/batch-nav";
import { PrintButton } from "@/components/print-button";
import { Badge, Callout, Card, CardBody, CardHeader, Metric } from "@/components/ui";
import { api } from "@/lib/api";
import {
  CATEGORY_LABELS,
  count,
  dateTime,
  money,
  percent,
  titleize,
} from "@/lib/format";

export const dynamic = "force-dynamic";

/**
 * A single printable page: the numbers a judge or auditor would want as a
 * leave-behind, without clicking through five other pages to assemble them.
 * "Printable" here means the browser's own print-to-PDF — no PDF-generation
 * dependency, no server-side rendering step. `print:` utility classes hide
 * interactive chrome (nav, the print button itself) on the printed page and
 * a print-only header takes their place.
 */
export default async function BatchSummaryPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const batch = await api.batch(id);
  if (!batch) notFound();

  const briefings = await api.briefings(id);
  const briefing = briefings?.[0] ?? null;
  const metrics = batch.metrics;

  return (
    <div className="flex flex-col gap-6">
      <div className="print:hidden">
        <BatchNav batch={batch} active="summary" />
      </div>

      <div className="hidden flex-col gap-1 border-b border-line pb-3 print:flex">
        <div className="text-sm font-semibold text-ink">ReconProof — batch summary</div>
        <div className="text-xs text-ink-3">
          {batch.name} · generated {dateTime(new Date().toISOString())}
        </div>
      </div>

      <div className="flex items-center justify-between">
        <h2 className="text-base font-semibold text-ink">{batch.name}</h2>
        <PrintButton />
      </div>

      {!metrics ? (
        <Card>
          <CardBody>
            <Callout tone="review" title="This batch has not been reconciled">
              A summary needs a completed run — there are no metrics to report yet.
            </Callout>
          </CardBody>
        </Card>
      ) : (
        <>
          <Card>
            <CardHeader title="Headline metrics" />
            <CardBody className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              <Metric
                label="Automatic match rate"
                value={percent(metrics.automatic_match_rate)}
                tone="proven"
              />
              <Metric
                label="Settlement value traced"
                value={percent(metrics.money_weighted_rate)}
                tone="accent"
              />
              <Metric
                label="Unexplained"
                value={money(metrics.unexplained)}
                tone="review"
              />
              <Metric
                label="Rejected by rules"
                value={count(metrics.rejected_by_invariant)}
                tone={metrics.rejected_by_invariant > 0 ? "blocked" : "neutral"}
              />
            </CardBody>
          </Card>

          <Card>
            <CardHeader
              title="Every rupee accounted for"
              description="Two distinct claims — traced automatically, and fully represented in the queue if not — reported separately rather than folded into one number."
            />
            <CardBody className="flex flex-wrap gap-6">
              <div>
                <div className="text-[11px] uppercase tracking-wider text-ink-3">
                  Auto-traced by value
                </div>
                <div className="tabular text-lg font-semibold text-ink">
                  {percent(metrics.money_weighted_rate)}
                </div>
                <div className="text-xs text-ink-3">
                  {money(metrics.settlement_value_traced)} of {money(metrics.settlement_value)}
                </div>
              </div>
              <div>
                <div className="text-[11px] uppercase tracking-wider text-ink-3">
                  Fully accounted for
                </div>
                {metrics.unresolved_value_fully_represented ? (
                  <Badge tone="proven">Yes — nothing missing</Badge>
                ) : (
                  <Badge tone="blocked">No — queue is short of the total</Badge>
                )}
              </div>
            </CardBody>
          </Card>

          {briefing ? (
            <Card>
              <CardHeader
                title="Batch health briefing"
                description={`Generated by the ${briefing.provider} provider from measured facts only`}
              />
              <CardBody className="flex flex-col gap-3">
                <p className="text-sm leading-relaxed text-ink">{briefing.headline}</p>
                <div className="whitespace-pre-line text-xs leading-relaxed text-ink-2">
                  {briefing.body}
                </div>
              </CardBody>
            </Card>
          ) : null}

          <Card>
            <CardHeader title="Unresolved value by cause" />
            <CardBody className="flex flex-col gap-2">
              {Object.entries(metrics.exceptions_by_category)
                .sort((a, b) => b[1] - a[1])
                .map(([category, categoryCount]) => (
                  <div
                    key={category}
                    className="flex items-center justify-between gap-3 rounded-lg border border-line bg-surface-2/40 px-3 py-2"
                  >
                    <span className="text-xs text-ink-2">
                      {CATEGORY_LABELS[category] ?? titleize(category)}
                    </span>
                    <span className="tabular text-xs font-medium text-ink">
                      {count(categoryCount)}
                    </span>
                  </div>
                ))}
            </CardBody>
          </Card>

          <Card>
            <CardHeader title="Provenance" />
            <CardBody className="grid grid-cols-2 gap-3 text-xs text-ink-2 sm:grid-cols-4">
              <div>
                <div className="text-[11px] uppercase tracking-wider text-ink-3">Scorer</div>
                <div className="text-ink">{metrics.scorer}</div>
              </div>
              <div>
                <div className="text-[11px] uppercase tracking-wider text-ink-3">
                  Risk budget
                </div>
                <div className="text-ink">{metrics.risk_budget ?? "—"}</div>
              </div>
              <div>
                <div className="text-[11px] uppercase tracking-wider text-ink-3">
                  Policy version
                </div>
                <div className="text-ink">{batch.policy_version ?? "—"}</div>
              </div>
              <div>
                <div className="text-[11px] uppercase tracking-wider text-ink-3">
                  Model version
                </div>
                <div className="text-ink">{batch.model_version ?? "—"}</div>
              </div>
            </CardBody>
          </Card>
        </>
      )}
    </div>
  );
}
