import { notFound } from "next/navigation";
import Link from "next/link";

import { BatchNav } from "@/components/batch-nav";
import { RunBatchButton } from "@/components/run-batch";
import {
  Badge,
  Bar,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Metric,
  Mono,
  Table,
  Td,
  Th,
} from "@/components/ui";
import { api } from "@/lib/api";
import {
  CATEGORY_LABELS,
  bytes,
  count,
  money,
  percent,
  RECORD_KIND_LABELS,
  titleize,
} from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function BatchOverviewPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const batch = await api.batch(id);
  if (!batch) notFound();

  const [briefings, exceptions] = await Promise.all([
    api.briefings(id),
    api.exceptions(`?batch_id=${id}&limit=5`),
  ]);
  const metrics = batch.metrics;
  const briefing = briefings?.[0] ?? null;

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <BatchNav batch={batch} active="overview" />
        <RunBatchButton batchId={batch.id} status={batch.status} />
      </div>

      {metrics ? (
        <>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <Card>
              <CardBody>
                <Metric
                  label="Automatic match rate"
                  value={percent(metrics.automatic_match_rate)}
                  tone="proven"
                  hint={`${count(metrics.auto_accepted)} of ${count(
                    metrics.auto_accepted + metrics.sent_to_review,
                  )} decided links`}
                />
                <div className="mt-3">
                  <Bar value={metrics.automatic_match_rate} tone="proven" />
                </div>
              </CardBody>
            </Card>
            <Card>
              <CardBody>
                <Metric
                  label="Settlement value traced"
                  value={percent(metrics.money_weighted_rate)}
                  tone="accent"
                  hint={`${money(metrics.settlement_value_traced)} of ${money(
                    metrics.settlement_value,
                  )}`}
                />
                <div className="mt-3">
                  <Bar value={metrics.money_weighted_rate} tone="accent" />
                </div>
              </CardBody>
            </Card>
            <Card>
              <CardBody>
                <Metric
                  label="Unexplained"
                  value={money(metrics.unexplained)}
                  tone="review"
                  hint={`Queue itemises ${money(metrics.exception_total)}`}
                />
                <div className="mt-3">
                  {metrics.unresolved_value_fully_represented ? (
                    <Badge tone="proven">Fully accounted for</Badge>
                  ) : (
                    <Badge tone="blocked">Queue is short of the total</Badge>
                  )}
                </div>
              </CardBody>
            </Card>
            <Card>
              <CardBody>
                <Metric
                  label="Rejected by rules"
                  value={count(metrics.rejected_by_invariant)}
                  tone={metrics.rejected_by_invariant > 0 ? "blocked" : "neutral"}
                  hint="Links an accounting invariant refused outright"
                />
                <div className="mt-3 text-[11px] leading-relaxed text-ink-3">
                  {metrics.forced_review_by_tie > 0
                    ? `${count(metrics.forced_review_by_tie)} forced to review by a tie`
                    : "No ties needed forcing"}
                </div>
              </CardBody>
            </Card>
          </div>

          {briefing ? (
            <Card>
              <CardHeader
                title="Batch health briefing"
                description={`Generated by the ${briefing.provider} provider from measured facts only`}
              />
              <CardBody className="flex flex-col gap-4">
                <p className="text-sm leading-relaxed text-ink">
                  {briefing.headline}
                </p>
                <div className="whitespace-pre-line text-xs leading-relaxed text-ink-2">
                  {briefing.body}
                </div>
                {briefing.recommended_actions.length > 0 ? (
                  <div>
                    <div className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-ink-3">
                      Recommended next steps
                    </div>
                    <ul className="flex flex-col gap-1.5">
                      {briefing.recommended_actions.map((action) => (
                        <li
                          key={action}
                          className="flex gap-2 text-xs leading-relaxed text-ink-2"
                        >
                          <span aria-hidden className="text-accent">
                            →
                          </span>
                          <span>{action}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : null}
              </CardBody>
            </Card>
          ) : null}

          <div className="grid gap-6 lg:grid-cols-2">
            <Card>
              <CardHeader
                title="How each link was decided"
                description="Deterministic matching resolves what identifiers prove; only the remainder is scored."
              />
              <CardBody className="flex flex-col gap-3">
                <StageRow
                  label="Identifier matches"
                  value={count(metrics.exact_links)}
                  note="Two records carry the same reference, or a chain of references implies the link"
                  tone="proven"
                />
                <StageRow
                  label="Candidates generated"
                  value={count(metrics.candidates_generated)}
                  note="Proposed only for records deterministic matching could not resolve"
                  tone="accent"
                />
                <StageRow
                  label="Displaced by global assignment"
                  value={count(metrics.displaced_by_assignment)}
                  note="A competing record had a stronger claim to the same counterpart"
                  tone="neutral"
                />
                <StageRow
                  label="Rejected by an invariant"
                  value={count(metrics.rejected_by_invariant)}
                  note="Financially impossible regardless of model confidence"
                  tone="blocked"
                />
                <div className="mt-1 border-t border-line pt-3 text-[11px] leading-relaxed text-ink-3">
                  Scorer: {metrics.scorer}
                  {metrics.risk_budget !== null
                    ? ` · risk budget ${metrics.risk_budget}`
                    : ""}
                  {batch.policy_version ? ` · policy ${batch.policy_version}` : ""}
                </div>
              </CardBody>
            </Card>

            <Card>
              <CardHeader
                title="Unresolved value by cause"
                description="Every open item carries the amount it leaves unexplained."
              />
              <CardBody className="flex flex-col gap-2.5">
                {Object.entries(metrics.exceptions_by_category)
                  .sort((a, b) => b[1] - a[1])
                  .map(([category, categoryCount]) => (
                    <div
                      key={category}
                      className="flex items-center justify-between gap-3 rounded-lg border border-line bg-surface-2/40 px-3 py-2"
                    >
                      <span className="text-xs text-ink-2">
                        {CATEGORY_LABELS[category] ?? titleize(category)}
                      </span>
                      <span className="tabular text-xs font-medium text-ink">
                        {count(categoryCount)}
                      </span>
                    </div>
                  ))}
                <Link
                  href={`/batches/${batch.id}/exceptions`}
                  className="mt-1 text-xs font-medium text-accent hover:underline"
                >
                  Open the exception queue →
                </Link>
              </CardBody>
            </Card>
          </div>

          <Card>
            <CardHeader
              title="Source files"
              description="Content-addressed on ingest, so a byte-identical re-upload is recognised and ignored."
            />
            <Table>
              <thead>
                <tr>
                  <Th>Source</Th>
                  <Th>File</Th>
                  <Th align="right">Rows accepted</Th>
                  <Th align="right">Rejected</Th>
                  <Th align="right">Size</Th>
                  <Th>SHA-256</Th>
                </tr>
              </thead>
              <tbody>
                {batch.sources.map((source) => (
                  <tr key={source.id}>
                    <Td className="whitespace-nowrap text-ink">
                      {titleize(source.source_kind)}
                    </Td>
                    <Td>
                      <Mono>{source.filename}</Mono>
                    </Td>
                    <Td align="right" className="tabular">
                      {count(source.accepted_rows)}
                    </Td>
                    <Td align="right" className="tabular">
                      {source.rejected_rows > 0 ? (
                        <span className="text-blocked">
                          {count(source.rejected_rows)}
                        </span>
                      ) : (
                        <span className="text-ink-3">0</span>
                      )}
                    </Td>
                    <Td align="right" className="tabular">
                      {bytes(source.byte_size)}
                    </Td>
                    <Td>
                      <Mono title={source.content_sha256}>
                        {source.content_sha256.slice(0, 12)}
                      </Mono>
                    </Td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </Card>

          <Card>
            <CardHeader title="Records by canonical kind" />
            <CardBody className="grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-7">
              {Object.entries(metrics.records_by_kind).map(([kind, kindCount]) => (
                <Metric
                  key={kind}
                  label={RECORD_KIND_LABELS[kind] ?? titleize(kind)}
                  value={count(kindCount)}
                />
              ))}
            </CardBody>
          </Card>

          {exceptions && exceptions.length > 0 ? (
            <Card>
              <CardHeader
                title="Largest open items"
                description="Ordered by unresolved value, which is the order a finance team works in."
              />
              <Table>
                <thead>
                  <tr>
                    <Th>Cause</Th>
                    <Th align="right">Amount</Th>
                    <Th>Summary</Th>
                    <Th />
                  </tr>
                </thead>
                <tbody>
                  {exceptions.map((item) => (
                    <tr key={item.id} className="hover:bg-surface-2/50">
                      <Td className="whitespace-nowrap">
                        <Badge tone="review">
                          {CATEGORY_LABELS[item.category] ?? titleize(item.category)}
                        </Badge>
                      </Td>
                      <Td align="right" className="tabular whitespace-nowrap text-ink">
                        {money(item.amount)}
                      </Td>
                      <Td className="max-w-xl text-xs leading-relaxed">
                        {item.summary}
                      </Td>
                      <Td align="right">
                        <Link
                          href={`/exceptions/${item.id}`}
                          className="whitespace-nowrap text-xs font-medium text-accent hover:underline"
                        >
                          Review →
                        </Link>
                      </Td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            </Card>
          ) : null}
        </>
      ) : (
        <Card>
          <CardBody>
            <Callout tone="review" title="This batch has not been reconciled">
              Its records are ingested but no run has completed, so there are no
              metrics to report. Batches used for fitting and calibration are ingested
              without being reconciled.
            </Callout>
          </CardBody>
        </Card>
      )}
    </div>
  );
}

function StageRow({
  label,
  value,
  note,
  tone,
}: {
  label: string;
  value: string;
  note: string;
  tone: "proven" | "accent" | "neutral" | "blocked";
}) {
  const dot = {
    proven: "bg-proven",
    accent: "bg-accent",
    neutral: "bg-line-strong",
    blocked: "bg-blocked",
  }[tone];
  return (
    <div className="flex items-start gap-3">
      <span aria-hidden className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${dot}`} />
      <div className="min-w-0 flex-1">
        <div className="flex items-baseline justify-between gap-3">
          <span className="text-xs font-medium text-ink-2">{label}</span>
          <span className="tabular text-sm font-semibold text-ink">{value}</span>
        </div>
        <p className="mt-0.5 text-[11px] leading-relaxed text-ink-3">{note}</p>
      </div>
    </div>
  );
}
